Assignment2: formulaExpander.c File Reference
formulaExpander.c File Reference
Implementation for expanding, validating, and processing chemical formulas.
#include "formulaExpander.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
Macros
#define MAX_FORMULA_LENGTH 1024
Buffer size for reading formulas.
Functions
void formulaProcessor (const char *inputFile, const char *outputFile)
Processes chemical formulas from a file and writes the expanded formulas to another file.
void countProtons (const char *inputFile, const char *outputFile, Element periodicTable[])
Counts the total number of protons in the chemical formulas found in a file.
bool validateParentheses (const char *inputFile)
Validates the balance of parentheses in each formula from a file.
Detailed Description
Implementation for expanding, validating, and processing chemical formulas.
This .c file provides implementations for expanding chemical formulas to their full representations, validating the balance of parentheses in chemical formulas, and counting protons based on expanded formulas using data from a periodic table. It utilizes stack operations extensively to manage elements and parentheses during the parsing and expansion processes.
Dependencies:
formulaExpander.h: Header file with declarations for the functions implemented here.
periodicTable.h: Provides support for element data management.
unionStack.h: Defines stack operations used for managing elements and parentheses.
Functions:
processFormula(): Processes a single chemical formula to expand based on multipliers and parentheses.
formulaProcessor(): Reads formulas from a file, processes them, and writes results to another file.
countProtons(): Calculates and writes the total number of protons for expanded formulas.
validateParentheses(): Checks if the parentheses in the chemical formulas are balanced.
Author
Panagiotis Tsembekis
Bug:
No known bugs.
Macro Definition Documentation
MAX_FORMULA_LENGTH
#define MAX_FORMULA_LENGTH 1024
Buffer size for reading formulas.
Function Documentation
countProtons()
void countProtons (const char * inputFile, const char * outputfile, Element periodicTable[])
Counts the total number of protons in the chemical formulas found in a file.
This function reads expanded chemical formulas from a file and uses the provided periodic table to count the total number of protons for each formula. The result is written to the output file provided.
Parameters
inputFile The path to the input file containing the chemical formulas (not expanded).
outputFile The path to the output file where the proton counts will be written.
periodicTable An array of Element structures representing the periodic table, used to look up atomic numbers.
{
    char tempFile[] = "expanded.txt"; // file that we will store the expanded formulas
    FILE *fp = fopen(tempFile, "w+"); // file for read&write (created if not existant)
    if(fp == NULL){
        perror("Unable to create file to store expanded formulas");
        exit(EXIT_FAILURE);
    }
    formulaProcessor(inputFile, tempFile); // expand the formulas
    FILE *fout = fopen(outputFile, "w");
    if(fout == NULL){
        perror("Unable to open output file for count protons.");
        fclose(fp);
        exit(EXIT_FAILURE);
    }
    char formula[MAX_FORMULA_LENGTH];
    while(fgets(formula, sizeof(formula), fp)){ // read each formula 1 by 1
        const char *p = formula;
        int totalAtomicNumber = 0;
        while(*p != '\0'){ // iterate up to the end
            if (isalpha(*p)) { // if is letter
                Element element;
                element.atomicNumber = 0;
                if(isupper(*p) && islower(*(p + 1)) && islower(*(p + 2))){ // three-letter elements
                    element.chemSymbol[0] = *p;
                    element.chemSymbol[1] = *(p + 1);
                    element.chemSymbol[2] = *(p + 2);
                    element.chemSymbol[3] = '\0';
                p += 2;
                } else if (isupper(*p) && islower(*(p + 1))) { // two-letter elements
                    element.chemSymbol[0] = *p;
                    element.chemSymbol[1] = *(p + 1);
                    element.chemSymbol[2] = '\0';
                    p++;  // skip 2nd letter since we handled it above
                } else {
                    // Single-letter element
                    element.chemSymbol[0] = *p;
                    element.chemSymbol[1] = '\0';
                }
                // After constructing the element, look-up its atomic number
                element.atomicNumber = getAtomicNumber(periodicTable, MAX_ELEMENTS, element.chemSymbol);
                totalAtomicNumber += element.atomicNumber;
            }
            p++; // move to next character of formula
        }
        fprintf(fout, "%d\n", totalAtomicNumber); // print formula's atomic number in output file
    }
    fclose(fp);
    fclose(fout);
}
References Element::atomicNumber, Element::chemSymbol, formulaProcessor(), getAtomicNumber(), MAX_ELEMENTS, and MAX_FORMULA_LENGTH.
Referenced by main().
formulaProcessor()
void formulaProcessor (const char * inputFile, const char * outputFile)
Processes chemical formulas from a file and writes the expanded formulas to another file.
This function reads chemical formulas from a specified input file, expands them, and writes the expanded formulas to a specified output file. The expansion process involves replacing compact chemical notation with the full repeated elements.
Parameters
inputFile The path to the input file containing original compact formulas.
outputFile The path to the output file where expanded formulas will be written.
{
    FILE *fin = fopen(inputFile, "r"); // open file for read-only
    if (fin == NULL) { // ensure proper file opening
        perror("Unable to open input file for formula expansion.");
        return;
    }
    FILE *fout = fopen(outputFile, "w"); // open file for write-only
    if (fout == NULL) { // ensure proper file opening
        perror("Unable to open output file for writing.");
        fclose(fin);
        return;
    }
    char formula[MAX_FORMULA_LENGTH];
    while (fgets(formula, sizeof(formula), fin)) {
        formula[strcspn(formula, "\n")] = '\0'; // replace newline character with terminating character
        char *expandedFormula = processFormula(formula); // calculate expanded formula
        if (expandedFormula) { // check wether the formula returned is null (error) or not and print accordingly
            fprintf(fout, "%s\n", expandedFormula);
            free(expandedFormula);
        } else {
            printf("Error processing formula: %s\n", formula);
        }
    }
    fclose(fin);
    fclose(fout);
}
References MAX_FORMULA_LENGTH.
Referenced by countProtons(), and main().
validateParentheses()
bool validateParentheses (const char * inputFile)
Validates the balance of parentheses in each formula from a file.
This function opens a file, reads each line as a formula, and checks whether the parentheses in the formula are balanced by calling checkParentheses. If an imbalance is found, it prints an error message indicating the line number. The function returns true if all formulas in the file are balanced, and false otherwise.
Parameters
inputFile A null-terminated string representing the path to the input file.
Returns
true if all formulas in the file have balanced parentheses, false otherwise.
{
    FILE *fp = fopen(inputFile, "r"); // open file for reading the formulas
    if (fp == NULL) {
        perror("Error opening file for parentheses validation.");
        return EXIT_FAILURE;
    }
    char formula[MAX_FORMULA_LENGTH];
    int lineIndex = 0;
    bool overallValid = true; // assume that all formulas are balanced
    while (fgets(formula, sizeof(formula), fp) != NULL) { // read line-by-line
        lineIndex++;
        if (formula[strlen(formula) - 1] == '\n') {
            formula[strlen(formula) - 1] = '\0'; // Remove the newline character, if present
        }
        bool valid = checkParentheses(formula);
        if (!valid) { // If not valid, print the error message
            printf("Parentheses NOT balanced in line: %d\n", lineIndex);
            overallValid = false;
        }
    }
    fclose(fp);
    return overallValid; // return overall parentheses balance of file
}
References MAX_FORMULA_LENGTH.
Referenced by main().