Assignment2: periodicTable.c File Reference
periodicTable.c File Reference
Provides implementations for managing and accessing periodic table data.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "periodicTable.h"
Functions
int loadPeriodicTable (const char *filename, Element elements[])
Loads the periodic table from a file.
void sortPeriodicTable (Element elements[], int numElements)
Sorts the periodic table by atomic number.
int getAtomicNumber (Element elements[], int n, const char *symbol)
Retrieves the atomic number of an element based on its chemical symbol.
Detailed Description
Provides implementations for managing and accessing periodic table data.
Implements functions to load a periodic table from a file, sort it by atomic number, and retrieve the atomic number of an element given its chemical symbol.
Dependencies:
periodicTable.h: Provides support for element data management.
Author
Panagiotis Tsembekis
Bug:
No known bugs.
Function Documentation
getAtomicNumber()
int getAtomicNumber (Element elements[], int n, const char * symbol)
Retrieves the atomic number of an element based on its chemical symbol.
This function searches an array of Element structs for an element with the specified chemical symbol and returns its atomic number.
Parameters
[in] elements The array of elements to search through.
[in] n The number of elements in the array.
[in] symbol The chemical symbol to search for.
Returns
int The atomic number of the element, or -1 if the symbol was not found.
{
    for (int i = 0; i < n; i++) { // iterate elements table to find the requested symbol
        if (strcmp(elements[i].chemSymbol, symbol) == 0) { // if a match is found return its atomic number
            return elements[i].atomicNumber;
        }
    }
    return -1;  // return -1 if element not found
}
References Element::atomicNumber.
Referenced by countProtons().
loadPeriodicTable()
int loadPeriodicTable (const char * filename, Element elements[])
Loads the periodic table from a file.
This function reads element data (chemical symbol and atomic number) from a specified file and loads it into an array of Element structs.
Parameters
[in] filename The name of the file containing element data.
[out] elements An array to store the loaded elements.
Returns
int The number of elements successfully loaded, or 'EXIT_FAILURE' if the file could not be opened.
{
    FILE *file = fopen(filename, "r"); // open file to read elements
    if (file == NULL) {
        perror("Unable to open file to read periodic table elements.");
        return EXIT_FAILURE;
    }
    char symbol[4];
    int atomicNumber, index = 0;
    while (index < MAX_ELEMENTS && fscanf(file, "%3s %d", symbol, &atomicNumber) == 2) { // read element symbol & atomic number
        symbol[sizeof(symbol) - 1] = '\0';  // termination character
        if (strlen(symbol) > 3) { // handle invalid elements
            fprintf(stderr, "Error: Chemical symbol '%s' exceeds maximum length.\n", symbol);
            continue;  // skip this
        }
        // Construct element that will be stored in elements[index]
        strncpy(elements[index].chemSymbol, symbol, sizeof(elements[index].chemSymbol) - 1); // element name = symbol read
        elements[index].chemSymbol[sizeof(elements[index].chemSymbol) - 1] = '\0';  // termination character
        elements[index].atomicNumber = atomicNumber; // assign atomic number
        index++;
    }
    fclose(file);
    return index; // return index to keep track in parseFormula.c of how many elements we've read
}
References Element::atomicNumber, Element::chemSymbol, and MAX_ELEMENTS.
Referenced by main().
sortPeriodicTable()
void sortPeriodicTable (Element elements[], int numElements)
Sorts the periodic table by atomic number.
This function sorts an array of Element structs in ascending order based on their atomic numbers, using the bubble sort algorithm.
Parameters
[in,out] elements An array of elements to be sorted.
[in] numElements The number of elements in the array.
{
    int i, j;
    Element temp;
    for (i = 0; i < numElements - 1; i++) {
        for (j = 0; j < numElements - i - 1; j++) {
            if (elements[j].atomicNumber > elements[j + 1].atomicNumber) { // sort in ascending order
                // Swap element[i] with element[i + 1]
                temp = elements[j];
                elements[j] = elements[j + 1];
                elements[j + 1] = temp;
            }
        }
    }
}
Referenced by main().